name: Train on AWS SageMaker

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload code to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: skin-lesion-ham10000
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1
        SOURCE_DIR: ./
        DEST_DIR: code/latest/

    - name: Trigger training in SageMaker
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        JOB_NAME=cnn-ham-$(date +%s)

        aws sagemaker create-training-job \
          --training-job-name $JOB_NAME \
          --algorithm-specification TrainingImage=763104351884.dkr.ecr.eu-central-1.amazonaws.com/tensorflow-training:2.13-cpu-py310,TrainingInputMode=File \
          --role-arn $SAGEMAKER_ROLE_ARN \
          --input-data-config '[
            {
              "ChannelName":"training",
              "DataSource":{
                "S3DataSource":{
                  "S3DataType":"S3Prefix",
                  "S3Uri":"s3://skin-lesion-ham10000/",
                  "S3DataDistributionType":"FullyReplicated"
                }
              }
            },
            {
              "ChannelName":"code",
              "DataSource":{
                "S3DataSource":{
                  "S3DataType":"S3Prefix",
                  "S3Uri":"s3://skin-lesion-ham10000/code/latest/",
                  "S3DataDistributionType":"FullyReplicated"
                }
              }
            }
          ]' \
          --output-data-config "{\"S3OutputPath\":\"s3://skin-lesion-ham10000/output\"}" \
          --resource-config '{"InstanceType":"ml.m5.large","InstanceCount":1,"VolumeSizeInGB":20}' \
          --stopping-condition '{"MaxRuntimeInSeconds":1800}' \
          --region eu-central-1
