name: Train on AWS SageMaker

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: skin-lesion-ham10000-euc1
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Rename train.py to train (required by SageMaker Script Mode)
      run: mv train.py train

    - name: Upload code to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        SOURCE_DIR: ./
        DEST_DIR: code/latest/

    - name: Trigger training in SageMaker
      run: |
        echo "ROLE ARN: [$SAGEMAKER_ROLE_ARN]"
        echo "Length: ${#SAGEMAKER_ROLE_ARN}"

        JOB_NAME=cnn-ham-$(date +%s)

        aws sagemaker create-training-job \
          --training-job-name $JOB_NAME \
          --algorithm-specification TrainingImage=763104351884.dkr.ecr.eu-central-1.amazonaws.com/tensorflow-training:2.13-cpu-py310,TrainingInputMode=File \
          --role-arn "$SAGEMAKER_ROLE_ARN" \
          --input-data-config '[
            {
              "ChannelName":"train",
              "DataSource":{
                "S3DataSource":{
                  "S3DataType":"S3Prefix",
                  "S3Uri":"s3://skin-lesion-ham10000-euc1/HAM10000_sorted/train/",
                  "S3DataDistributionType":"FullyReplicated"
                }
              }
            },
            {
              "ChannelName":"val",
              "DataSource":{
                "S3DataSource":{
                  "S3DataType":"S3Prefix",
                  "S3Uri":"s3://skin-lesion-ham10000-euc1/HAM10000_sorted/val/",
                  "S3DataDistributionType":"FullyReplicated"
                }
              }
            },
            {
              "ChannelName":"code",
              "DataSource":{
                "S3DataSource":{
                  "S3DataType":"S3Prefix",
                  "S3Uri":"s3://skin-lesion-ham10000-euc1/code/latest/",
                  "S3DataDistributionType":"FullyReplicated"
                }
              }
            }
          ]' \
          --output-data-config "{\"S3OutputPath\":\"s3://skin-lesion-ham10000-euc1/output\"}" \
          --resource-config '{"InstanceType":"ml.m5.large","InstanceCount":1,"VolumeSizeInGB":20}' \
          --enable-managed-spot-training \
          --stopping-condition '{"MaxRuntimeInSeconds":1800,"MaxWaitTimeInSeconds":3600}' \
          --region $AWS_REGION
